
package employee.services;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeServiceImpl", targetNamespace = "http://services.employee/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeServiceImpl {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "loadEmp", targetNamespace = "http://services.employee/", className = "employee.services.LoadEmp")
    @ResponseWrapper(localName = "loadEmpResponse", targetNamespace = "http://services.employee/", className = "employee.services.LoadEmpResponse")
    @Action(input = "http://services.employee/EmployeeServiceImpl/loadEmpRequest", output = "http://services.employee/EmployeeServiceImpl/loadEmpResponse")
    public void loadEmp();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<employee.services.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeByBirthDate", targetNamespace = "http://services.employee/", className = "employee.services.GetEmployeeByBirthDate")
    @ResponseWrapper(localName = "getEmployeeByBirthDateResponse", targetNamespace = "http://services.employee/", className = "employee.services.GetEmployeeByBirthDateResponse")
    @Action(input = "http://services.employee/EmployeeServiceImpl/getEmployeeByBirthDateRequest", output = "http://services.employee/EmployeeServiceImpl/getEmployeeByBirthDateResponse")
    public List<Employee> getEmployeeByBirthDate(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<employee.services.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeByLastName", targetNamespace = "http://services.employee/", className = "employee.services.GetEmployeeByLastName")
    @ResponseWrapper(localName = "getEmployeeByLastNameResponse", targetNamespace = "http://services.employee/", className = "employee.services.GetEmployeeByLastNameResponse")
    @Action(input = "http://services.employee/EmployeeServiceImpl/getEmployeeByLastNameRequest", output = "http://services.employee/EmployeeServiceImpl/getEmployeeByLastNameResponse")
    public List<Employee> getEmployeeByLastName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<employee.services.Employee>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployeeByFirstName", targetNamespace = "http://services.employee/", className = "employee.services.GetEmployeeByFirstName")
    @ResponseWrapper(localName = "getEmployeeByFirstNameResponse", targetNamespace = "http://services.employee/", className = "employee.services.GetEmployeeByFirstNameResponse")
    @Action(input = "http://services.employee/EmployeeServiceImpl/getEmployeeByFirstNameRequest", output = "http://services.employee/EmployeeServiceImpl/getEmployeeByFirstNameResponse")
    public List<Employee> getEmployeeByFirstName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
